# ============================================
# Home Network Lab - Network Report Generator
# ============================================

$ReportPath = ".\reports\network-report.txt"

# Create reports folder
New-Item -ItemType Directory -Path ".\reports" -Force | Out-Null

# Computer Name
$ComputerName = $env:COMPUTERNAME

# Date
$Date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Active Network Adapter
$Config = Get-NetIPConfiguration |
Where-Object { $_.IPv4Address -ne $null } |
Select-Object -First 1

$IPv4 = $Config.IPv4Address.IPAddress
$Gateway = $Config.IPv4DefaultGateway.NextHop
$Subnet = $Config.IPv4Address.PrefixLength

# DNS Servers
$DNS = (Get-DnsClientServerAddress -AddressFamily IPv4 |
Where-Object {$_.ServerAddresses} |
Select-Object -First 1).ServerAddresses

# Build Report
$Report = @"
========================================
HOME NETWORK REPORT
========================================

Computer Name
-------------
$ComputerName

Date
----
$Date

IPv4 Address
------------
$IPv4

Subnet Prefix
-------------
/$Subnet

Default Gateway
---------------
$Gateway

DNS Servers
-----------
$($DNS -join "`r`n")

========================================
Generated by PowerShell
========================================
"@

# Save as UTF-8
Set-Content -Path $ReportPath -Value $Report -Encoding UTF8

Write-Host ""
Write-Host "Report created successfully!" -ForegroundColor Green
Write-Host $ReportPath